worker_processes  auto;
daemon off;
worker_rlimit_nofile 1048576;
events {
    worker_connections  65535;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    gzip_static   on;
    gzip_proxied  any;

    server {
        listen       80;
        server_name  localhost;

        root /var/www;
        index index.html;

        # Serve static files if they exist, else fallback to index.html (SPA support)
        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache, must-revalidate";
        }

        # Error pages
        error_page 404 /index.html;
        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root /var/www;
        }
    }
}
