-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpQtPGJUuniHF+5nn
Q+AVXpAUomgvzK9eBw7vAw/kMw6gCgYIKoZIzj0DAQehRANCAAQ++LEIVosIKOyo
dK+X35u+fzIwDGr6oSYQtfT7DCmIdBVXBGrYNyXlLx7VYTIkIyJskKUK5s954kBv
8aYdTnOk
-----END PRIVATE KEY-----