import { configuration } from "../config";

export const EVENTNAMES = {
  CONNECTION: "connection",
  PUBLIC_CHAT: "publicChat",
  PRIVATE_CHAT: "privateChat",
  BROADCAST_MESSAGE: "broadcastMessage",
  ADD_PARTICIPANT: "addParticipants",
  END_MEETING: "endMeeting",
  MOVE_TO_WAITING_ROOM: "movetowaitroom",
  JOINMEETING: "joinMeeting",
  REMOVE_FROM_MEETING: "removeFromMeeting",
  MEETING_STATUS: "meetingStatus",
  MEET_NOW_STATUS: "meetnowStatus",
  HOST_STATUS: "hostStatus",
  CONNECTION_STATUS: "connectStatus",
  VM_SETTINGS:"vm_settings",
  RENAME_CHANGED: "nameChangeEvent",
  REMOVE_MULTIPLE_PARTICIPANTS: "removeMultipleParticipants",
  CHAT_SETTING: "chatSetting",
  GENERAL_SETTING: "generalSetting",
  GET_CHAT_LIST: "getChats",
  ACTIVE_SPEAKER: "activeSpeaker",
  HAND_RAISE: "handRaise",
  HOST_CHANGED: 'hostChanged',
  ASSIGN_HOST: 'assignHost',
  ENABLE_RECORDING: 'enableRecording',
  LOWER_ALL_HAND_RAISE: 'lowerAllHandRaise',
  MULTIPLE_ENABLE_RECORDING: 'multipleEnableRecording',
  MULTIPLE_TO_WAITING_ROOM: 'multipleToWaitingRoom',
  WHITE_BOARD: 'whiteBoard',
  MAKE_AS_ADMIN: 'makeasAdmin',
  GET_WHITE_BOARD: 'getWhiteBoard',
  AUDIO_MUTE_UNMUTE: 'audioMuteUnmute',
  VIDEO_HIDE_SHOW: 'videoHideShow',
  MUTE_ALL: 'muteAll',
  HOST_JOINING: 'host_joining',
  AGENT_JOINING:"agent_joining",
  CUSTOMER_JOINING:"customer_joining",
  CUSTOMER_WAITING_ROOM:"customer_waiting_room",
  PARTICIPANT_MOVE: 'participant_move',
  PARTICIPANT_REMOVE: 'participant_remove',
  PARTICIPANT_JOINIG: 'participant_joining',
  USER_TERMINATED: 'user_action_terminated',
  USER_DISCONNECTED: 'user_action_disconnected',
  JOIN_INITIALIZED: 'join_initialized',
  END_MEETING_ALL: 'end_meeting_all',
  SERVER_FAILURE: 'server_failure',
  HOST_REQUEST_UNMUTE: 'hostRequestUnMute',
  HOST_REQUEST_UNMUTEALL: 'hostRequestUnMuteall',
  PARTICIPANT_REQUEST_UNMUTE: 'participantRequestUnMute',
  WAITINGROOM_RETRY: 'waitingroom_retry',
  AGAIN_RETRY_WATINGROOM: 'againRetryWaitingroom',
  ADMIT_ALL: 'admitAll',
  PARTICIPANT_REQUEST_RECORING: 'participantRequestRecording',
  START_RECORDING: 'startRecording',
  STOP_RECORDING: 'stopRecording',
  REMOVE_MEETING_NOTIFY: 'removeMeetingNotify',
  LAST_PERSON_LEFT: 'last_person_left',
  HOST_REJECT_RECORING_REQUEST: 'hostReject_recording_request',
  RECORDING_ACTION: 'recordingAction',
  START_CLOSE_CAPTION: 'startClosecaption',
  END_CLOSE_CAPTION: 'endClosecaption',
  CLOSE_CAPTION: 'closecaption',
  SEND_VOICE_DATA: 'sendVoicedata',
  CLOSE_CAPTION_ENDED: 'closeCaptionEnded',
  GET_TRANSCRIPTS: 'getTranscripts',
  CLOSE_CAPTION_STARTED: 'closeCaptionStarted',
  SCREEN_SHARE: 'screenShare',
  MIRROR_UPDATE: 'updateMirror',
  CLOSE_CAPTION_ON_REQUEST: 'closeCaptionOnRequest',
  STORE_CLOSE_CAPTION: 'storeClosecaption',
  UPDATE_TRANSCRIPT: 'updateTranscript',
  SEARCH_TRANSCRIPT: 'searchTranscript',
  FILTER_TRANSCRIPT: 'filterTranscript',
  TRANSLATE_TRANSCRIPT: 'translateTranscript',
  GET_KEYWORDS: 'getKeywords',
  ADD_KEYWORD: 'addKeyword',
  AUTOMATEDMINUTES: 'automatedMinutes',
  REMOVE_KEYWORD: 'removeKeyword',
  CONNECTION_FAILURE: 'connectionFailure',
  MANUALLY_DISCONNECT: 'manuallyDisconnect',
  RECONNECT_SCREENSHARE: 'reconnectScreenshare',
  UPDATE_PARTICIPANTLIST: 'updated_participant_list',
  UPDATE_PARTICIPANTLIST_SUCCESS: 'updated_participant_list_success',
  CLIENT_UPDATED_PARTICIPANTLIST: 'updated_participant_list',
  JOIN_SCREENSHARE: 'joinScreenshare',
  START_SCREENSHARE: 'screenshare_start',
  SCREENSHARE_STARTED: 'screenshare_started',
  SCREENSHARE_STOP: 'screenshare_stop',
  SCRENNSHARE_STOPPED: 'screenshare_stopped',
  SCRENNSHARE_DTLS_ERROR: 'screenshare_session_dtls_error',
  SCRENNSHARE_DTLS_SUCCESS: 'screenshare_session_dtls_reconnection_success',
  SCREENSHARE_USERJOINING_ERROR: 'screenshare_session_joining_error',
  SDP_RECEIVE_FROM_CLIENT: 'sdp_receive_from_client',
  SDP_SENT_TO_CLIENT: 'sdp_sent_to_client',
  SDP_UPDATE_REQUEST: 'sdp_update_request',
  SDP_UPDATE_RESPONSE: 'sdp_update_response',
  UPDATE_MEETING_TITLE: 'updateMeetingTitle',
  PARTICIPANT_REQUEST_SCREENSHARE: 'participantRequestScreenShare',
  HOST_REJECT_SCREENSHARE_REQUEST: 'hostRejectScreenShareRequest',
  HOST_ALLOW_SCREENSHARE: 'hostAllowScreenShare',
  PINNED_USER: 'pinnedUser',
  TILE_CHANGE_REQUEST: 'tile_change_request',
  TILE_CHANGE_RESPONSE: 'tile_change_response',
  POOR_NETWORK_EVENT: 'poor_network_detect',
  SCREENSHARE_VIDEO_REQ: 'screenshare_video_req',
  ACTIVE_SPEAKER_VIDEO_REQ: 'active_speaker_video_req',
  VIDEO_RESOLUTION_REQ: 'video_resolution_req',
  CC_LANG_UPDATE: "updateCCLang",
  RECORDING_START: "recording_start",
  RECORDING_STOP: "recording_stop",
  RECORDING_PAUSE: "recording_pause",
  RECORDING_RESUME: "recording_resume",
  FINAL_DENY_JOIN: "final_deny_join",
  HOST_REQUEST_UNHIDE: 'hostRequestUnHide',
  ACTIVE_SPEAKER_INFO: 'active_speaker_info',
  REACTIONS: "reactions",
  REACTION_REMOVE: "reaction_remove",
  NON_VERBAL: "non_verbal",
  MIC_LANGUAGE: 'micLanguage',
  VIDEO_ANNOUNCEMENT:"video_announcement",
  UPDATE_CANVAS_SIZE:"update_canvas_size",
  CO_BROWSER_REQ:"co_browser_req",
  CO_BROWSER_DECLINED:"co_browser_declined",
  CO_BROWSER_ACCEPTED:"co_browser_accepted",
  INSERT_REC_CC:"insert_rec_cc",
  TRANSFER_INITIATE:"transfer_initiate",
  TRANSFER_INIT_CONF:'transfer_init',
  TRANSFER_INITIATED:"transfer_initiated",
  HIDE_ALL:"hideAll",
  VERIFICATION_REQ:"verification_req",
  VERIFICATION_RES:"verification_res",
  VERIFICATION_DETAILS:"verification_details"
};

export const baseURL = configuration.restAPIURL
export const baseURLChat = configuration.restCHATAPIURL


console.log("baseURL >>>>>>>", baseURL);
export const ENDPOINTS = {
  getMeetingNoToken:'meetings/get_meeting_no_token',
  updateMeetingNoToken: 'meetings/update_meeting_socket/',
  getMeetingbyId: 'meetings/get_meeting',
  addParticpants: 'meetings/add_participants',
  hostStartmeeting: 'meetings/host_start_meeting',
  meetNow: 'meetings/meet_now',
  updateMeeting: 'meetings/edit_meeting_socket/',
  endMeeting: 'meetings/end_meeting',
  updateChatSetting: 'meetings/update_chatsetting/',
  updateWhiteBoard: 'meetings/update_whiteboard',
  getWhiteBoard: 'meetings/get_whiteboard',
  deleteGuestUser: 'user/delete_guest_user',
  getUserData: 'user/get_data',
  addKeyword: 'meetings/add_keyword',
  participantJoining: 'meetings/participant_status'
}

export const MEETING_STATUS = {
  CANCELLED: "Cancelled",
  UPCOMING: "Upcoming",
  ONGOING: "Ongoing",
  UNATTENDED: "Unattended",
  COMPLETED: "Completed",
  START: "Start",
  JOIN: "Join",
  PREVIOUS: "Previous",
  RECURRENCE: "Recurrence",
  MISSED: "Missed",
  ONGOIND_MEETING: "Ongoing Meeting",
  ALL: "All",
  REJOIN: "Rejoin"
};
