# ///////////////////////////////////////////////////////////////////////////
# 
#            Copyright 2020 by Vectone Mobile.
#            All rights reserved.
# 
# ///////////////////////////////////////////////////////////////////////////

export ACE_INCLUDE = -I/usr/local/include
#export XERCES_INCLUDE = -I/usr/local/include

# The BUILD_TYPE variable will tell whether debug build or optimized
# build is required.  The valid values are 'dbg' for debug build and
# 'opt' for optimized build.

export BUILD_TYPE = dbg
export ENABLE_PROFILING = no

CFLAGS = $(ACE_INCLUDE) #$(XERCES_INCLUDE)

ifeq ($(ENABLE_PROFILING),yes)
    CFLAGS += -pg
endif

ifeq ($(BUILD_TYPE),dbg)
    CFLAGS += -g
else
ifeq ($(BUILD_TYPE),opt)
    CFLAGS += -O2
endif
endif

CPP = g++ -Wall
DEPEND  = g++ -MM
